### ISSUE TITLE
How to make a readwrite copy of a readonly structure?

### ISSUE THREAD

**Issue by pmorch** [sanko/readonly#13]
Hi,

We have a large deep hash/array structure we don't want anybody to mess with and are considering marking it `Readonly`.

We would like however to make it possible for callers to clone (parts of) this structure to make their own read/write copies. But `Clone::clone` or `Storage::dclone` (two [popular](http://stackoverflow.com/questions/388187/whats-the-best-way-to-make-a-deep-copy-of-a-data-structure-in-perl) cloning techniques) seem to create clones that themselves are `Readonly`, which makes the cloning useless.

Is there any way to avoid that, other than using e.g. `JSON` or `Data::Dumper`?

    #!/usr/bin/perl
    use warnings;
    use Test::More;
    use Readonly;

    # Various ways to clone

    # These two create writable copies
    use JSON;
    use Data::Dumper;

    # These two create Readonly clones
    use Storable qw(dclone);
    use Clone qw(clone);

    Readonly my %ro => ( a => 1 );

    subtest 'simple modification - fails as expected' => sub {
        my $ok = eval { $ro{a} = 2; 1 };
        ok !$ok, 'not modified';
        like $@,qr{Modification},'correct exception';
    };

    subtest 'JSON encode/decode - passes' => sub {
        my $rw = decode_json(encode_json(\%ro));
        is_deeply $rw, { a => 1 }, '$rw has the right contents';
        my $ok = eval { $rw->{a} = 2; 1 };
        ok $ok, 'modified fine';
        ok ! $@, 'no exception';
    };

    subtest 'Data::Dumper - passes' => sub {
        my $rw;
        my $d = Data::Dumper->new([\%ro], ['rw']);
        eval $d->Dump();
        is_deeply $rw, { a => 1 }, '$rw has the right contents';
        my $ok = eval { $rw->{a} = 2; 1 };
        ok $ok, 'modified fine';
        ok ! $@, 'no exception';
    };

    subtest 'Storable::dclone - fails - dclones are Readonly' => sub {
        my $rw = dclone(\%ro);
        is_deeply $rw, { a => 1 }, '$rw has the right contents';
        my $ok = eval { $rw->{a} = 2; 1 };
        ok $ok, 'modified fine';
        ok ! $@, 'no exception';
    };

    subtest 'Clone::clone - fails - clones are Readonly' => sub {
        my $rw = clone(\%ro);
        is_deeply $rw, { a => 1 }, '$rw has the right contents';
        my $ok = eval { $rw->{a} = 2; 1 };
        ok $ok, 'modified fine';
        ok ! $@, 'no exception';
    };

    done_testing();

**Comment by pwr22** [comment]
I don't think it is bad to have a public way to make things non-readonly. Perl is a powerful and restrictive language but also permissive. Most restrictions are by convention and I think it fits quite well to have a way to turn Readonly off if you explicitly request it

That said, in this case, some kind of clone function seems more descriptive

**Comment by slavalitvinov** [comment]
A shallow copy works fine, although it gives only 1 level
    $new_hash = { %$readonly_hash };
