### ISSUE TITLE
Readonly my $foo = 2; # fails silently under recent versions of Perl and leaves $foo undef

### ISSUE THREAD

**Issue by ronaldxs** [sanko/readonly#18]
Based on the reply of the current maintainer of Readonly to my [comment on PerlMonks]( http://perlmonks.org/?node_id=1153807) I think I can reasonably assume it is appropriate to post an issue for the module on GitHub.  I proposed a preliminary patch on PerlMonks which the maintainer suggested he might take, but then mentioned he also be interested in a pull request.  I have forked the repository and hope to have a pull request with an improved patch including tests ready in a few weeks.

An abbreviated description of the problem based on the PerlMonks discussion follows:

The documented way to code a Readonly scalar is:
```Perl
Readonly my $sca => $initial_value;
```

In somewhat older versions of Perl like 5.14:
```Perl
Readonly my $foo = 2;
```
yeilded an error like:
Type of arg 1 to Readonly::Readonly must be one of \[$@%\] (not scalar assignment)

In new Perl versions the declaration does not cause an error but $foo is initialized to undef and attempting to use "$foo" with warnings will show uninitialized value warnings.

The change seems to be because of changed handling by newer versions of Perl in the subroutine prototypes used by Readonly.
Perl 5.14 and newer (and likely older) versions of Perl allow:
```Perl
perl -Mstrict -we 'sub f(\$){}; f(my $x)'
```

Perl 5.14 does not allow:
```Perl
perl -Mstrict -we 'sub f(\$){}; f(my $x = 3)'
```
and gives the familiar looking error “Type of arg 1 to main::f must be scalar (not scalar assignment)”.  Newer versions of Perl simply allow the subroutine proto code above which accounts for the changing behavior in Readonly between different versions of Perl.  Whereas allowing the proto example above to run in newer Perls could arguably be called a feature the change in behavior in Readonly could reasonably be classified as a bug.

Similarly to the example with a Readonly scalar the hash declaration below
```Perl
Readonly my %h = { key => 42 };
```
yields a warning, not an error, and leaves %h with an essentially useless value.  It might also be a candidate for a fatal exception.

The undocumented declarations:
```Perl
Readonly my @a = (1, 2, 3);
Readonly my %h = (key => 42); # note parens not braces
```
"work" and leave the variables with usable values.  It might be reasonable to have these cases issue warnings for consistency as long as there were an easy enough way to turn the warnings off since the usage doesn’t really cause trouble.

**Section on allowing assignment updated 2/22/2016.**

Another possible approach to the problem is allow all these assignments and have them set up the Readonly variables with correct values.  ~~As far as I know making the assignments work is technically feasible~~ but might cause confusion with
```Perl
Readonly::Scalar my $sca;
Readonly::Scalar my $sca = undef;
```
which are probably technically indistinguishable and the first case is supposed to be disallowed.  While this is not such a serious problem the example below is a real obstacle:
```Perl
Readonly::Array my @a = (3,5);
```
because
```Perl
sub f(\@){}; f(@a = (3,5));
```
is still disallowed unlike the scalar proto equivalent.

I am hoping to work on a fork that disallows the assignment syntax for consistency with older Perl releases.

**Comment by ronaldxs** [comment]
On closer examination and more testing it turns out:
```Perl
Readonly my @a = (3, 5);
Readonly my %h = (key => 42);
```
are broken too.  They are initialized by the assignment but the variables are not read only so:
```Perl
Readonly my @a = (3, 5); $a[1] = 7;
````
for example, runs without error or complaint.  If you use the documented "=>" syntax the examples work properly.

**Comment by sanko** [comment]
I've decided to send this to PAUSE as 2.01 today rather than a temporary dev build; I'm sure the tests will pass on smokers but stable will hopefully shake some bugs out of real world code.

Thanks again.
