### ISSUE TITLE
[PATCH] fix a typo in the POD

### ISSUE THREAD

**Issue by gregoa** [sanko/readonly#21]
In Debian we are currently applying the following patch to Readonly.
We thought you might be interested in it too.

    Description: fix a typo in the POD
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-05-06
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libreadonly-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by sanko** [comment]
Thanks.

Fixed in v2.02 and headed to PAUSE in about 12mins.

**Comment by gregoa** [comment]
On Fri, 06 May 2016 14:57:15 -0700, Sanko Robinson wrote:

> Thanks.
> Fixed in v2.02 and headed to PAUSE in about 12mins.

Great, thank you.


Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Funny Van Dannen: Billige Räusche
