### ISSUE TITLE
Warnings about ::_ARRAY() and ::_HASH() in 2.03

### ISSUE THREAD

**Issue by gregoa** [sanko/readonly#22]
As part of our tests of installed packages in Debian we're running `/usr/bin/perl -w -M"Readonly" -e 1 2>&1`. In 2.03 this outputs warnings:
```
# Readonly::_ARRAY() called too early to check prototype at /usr/share/perl5/Readonly.pm line 75.
# Readonly::_HASH() called too early to check prototype at /usr/share/perl5/Readonly.pm line 97.
```
which doesn't seem right :)

Cheers,
gregor, Debian Perl Group

**Comment by sanko** [comment]
Original author used them heavily and I kept them for historical reasons but I hate function prototypes... Obvious problem here is recusion inside functions with prototypes. Runtime, this would be fine but as a compile-time warning it's correct; I'll need to go through to see what needs to be predeclared (yuck).

What's worse is that entire section of code was originally designed to only run on perl 5.8.0 or lower and it's the reason Readonly used to be so slow. I'd love to 'accidentally' delete it but... historical reasons...

I'll roll out of bed and have a new version in PAUSE this afternoon. :)

**Comment by gregoa** [comment]
On Sat, 07 May 2016 07:17:08 -0700, Sanko Robinson wrote:

> I'll roll out of bed and have a new version in PAUSE this afternoon. :)

Thanks, and sorry for interrupting your recreation time :)


Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Dire Straits: Why Worry

**Comment by sanko** [comment]
Don't even mention it! You might be the only person who reports bugs that won't possibly break Readonly if they're fixed. Haha!

Let me know if v2.04 causes you any trouble.

**Comment by gregoa** [comment]
On Sat, 07 May 2016 08:48:41 -0700, Sanko Robinson wrote:

> Don't even mention it! You might be the only person who reports bugs that won't possibly break Readonly if they're fixed. Haha!

:)
 
> Let me know if v2.04 causes you any trouble.

This looks all good to me, thank you very much.
2.04 uploaded to Debian/unstable.

Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Eric Clapton: Cocaine

**Comment by petamem** [comment]
2.04 works here too, Perl 5.22.2 and 5.24.0 under Perlbrew, Gentoo64bit/GCC 5.3.0
2.03 behaved here exactly as reported by gregoa (that's how I came here).
